services:
  postgres:
    image: postgres:16
    container_name: pg16_ai_lab
    environment:
      POSTGRES_USER: bibhu
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: ai_lab
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bibhu -d ai_lab"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: ai-project-template-api
    container_name: ai_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://bibhu:supersecure@postgres:5432/ai_lab
    ports:
      - "8000:8000"

volumes:
  pgdata:
